return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "c",
      "lua",
      "vim",
      "wgsl",
      "help",
      "query",
      "html",
      "json",
      "typescript",
      "rust",
      "yaml",
      "tsx",
      "toml",
      "sql",
      "glimmer",
      "svelte",
      "regex",
      "javascript",
      "dockerfile",
    },
  },
}
